"""fix book constraints

Revision ID: 064d217d203d
Revises: 4e3945438289
Create Date: 2026-01-05 09:55:52.532258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064d217d203d'
down_revision: Union[str, Sequence[str], None] = '4e3945438289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_unique_constraint('unique_book_owner', 'books', ['isbn', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_book_owner', 'books', type_='unique')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###
